/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormGroup } from "./utils/model";
export namespace Components {
    interface ReactiveForm {
        "formGroup": FormGroup;
        "styleOptions": IStyleOptions;
    }
}
declare global {
    interface HTMLReactiveFormElement extends Components.ReactiveForm, HTMLStencilElement {
    }
    var HTMLReactiveFormElement: {
        prototype: HTMLReactiveFormElement;
        new (): HTMLReactiveFormElement;
    };
    interface HTMLElementTagNameMap {
        "reactive-form": HTMLReactiveFormElement;
    }
}
declare namespace LocalJSX {
    interface ReactiveForm {
        "formGroup": FormGroup;
        "onFormStatus"?: (event: CustomEvent<any>) => void;
        "onStatusChanges"?: (event: CustomEvent<any>) => void;
        "onValueChanges"?: (event: CustomEvent<any>) => void;
        "styleOptions"?: IStyleOptions;
    }
    interface IntrinsicElements {
        "reactive-form": ReactiveForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "reactive-form": LocalJSX.ReactiveForm & JSXBase.HTMLAttributes<HTMLReactiveFormElement>;
        }
    }
}
