/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormGroup } from "./utils/model";
export namespace Components {
    interface ReactiveForm {
        "additionalSelfHosted": any[];
        "attributeName": string;
        "formGroup": FormGroup;
    }
    interface TestComponent {
    }
}
export interface ReactiveFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReactiveFormElement;
}
declare global {
    interface HTMLReactiveFormElement extends Components.ReactiveForm, HTMLStencilElement {
    }
    var HTMLReactiveFormElement: {
        prototype: HTMLReactiveFormElement;
        new (): HTMLReactiveFormElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "reactive-form": HTMLReactiveFormElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface ReactiveForm {
        "additionalSelfHosted"?: any[];
        "attributeName"?: string;
        "formGroup": FormGroup;
        "onStatusChanges"?: (event: ReactiveFormCustomEvent<any>) => void;
        "onValueChanges"?: (event: ReactiveFormCustomEvent<any>) => void;
    }
    interface TestComponent {
    }
    interface IntrinsicElements {
        "reactive-form": ReactiveForm;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "reactive-form": LocalJSX.ReactiveForm & JSXBase.HTMLAttributes<HTMLReactiveFormElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
